version: '3.8'

services:
  # Web Server (Nginx)
  web:
    image: nginx:latest
    container_name: web-server
    ports:
      - "80:80"  # Exposes port 80 on the host to port 80 in the container
    volumes:
      - ./html:/usr/share/nginx/html  # Maps ./html directory to nginx's html directory
    depends_on:
      - db  # Ensures that the database is started before the web server

  # Database (MySQL)
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database  # Initializes a database
    ports:
      - "3306:3306"  # Exposes port 3306 for database access
    volumes:
      - db-data:/var/lib/mysql  # Stores data on the host machine so it persists across restarts

volumes:
  db-data:
    driver: local  # Defines the volume for MySQL data storage
